### PR TITLE
Clean up directory structure and packages

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Removed 'src' sub-directory as this isn't idiomatic and is unnecessary.
Renamed package 'msalgo' to simply 'msal' (the suffix is redundant).

### CODE REVIEW

**Review by keegan-caruso — APPROVED** [review]
LGTM, thanks for the change

**Review by jennyf19 — APPROVED** [review]
:shipit:

**Review by henrik-me — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@keegan-caruso do we wait for somebody to merge this?  I don't have permissions to merge.

**Comment by keegan-caruso** [comment]
@jhendrixMSFT  Thanks for the ping. Merged this.

**Pull request merged**
